/*
Notebook Navigator - Plugin for Obsidian
Copyright (c) 2025 Johan Sanneblad

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

=========================================================================
GENERATED FILE - DO NOT EDIT src/constants/notebookNavigatorIcon.ts
=========================================================================

Edit the SVG source instead: icon.svg
Generated by: scripts/build-icons.mjs
*/

// Icon identifier used with Obsidian's addIcon()/setIcon()
export const NOTEBOOK_NAVIGATOR_ICON_ID = 'notebook-navigator';

// Inner SVG content passed to addIcon() (Obsidian wraps this in <svg viewBox="0 0 100 100">)
export const NOTEBOOK_NAVIGATOR_ICON_SVG = `<g stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
    <rect x="19.88" y="12.42" width="66.42" height="75.21" rx="6.25" stroke-width="8"/>
    <g stroke-width="4">
      <line x1="13.29" y1="24.38" x2="28.5" y2="24.38"/>
      <line x1="13.29" y1="37.21" x2="28.5" y2="37.21"/>
      <line x1="13.29" y1="50" x2="28.5" y2="50"/>
      <line x1="13.29" y1="62.79" x2="28.5" y2="62.79"/>
      <line x1="13.29" y1="75.63" x2="28.5" y2="75.63"/>
    </g>
    <g stroke-width="3.5">
      <circle cx="28.5" cy="24.38" r="1.38"/>
      <circle cx="28.5" cy="37.21" r="1.38"/>
      <circle cx="28.5" cy="50" r="1.38"/>
      <circle cx="28.5" cy="62.79" r="1.38"/>
      <circle cx="28.5" cy="75.63" r="1.38"/>
    </g>
    <polygon points="49.23 53.33 32.68 49.08 66.53 34.18 53.71 69.38 49.23 53.33" fill="currentColor" stroke="none"/>
  </g>`;
