/*
 * Notebook Navigator - Plugin for Obsidian
 * Copyright (c) 2025-2026 Johan Sanneblad
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

const projectRoot = path.resolve(dirname, '..');
const entryPath = path.join(projectRoot, 'src', 'styles', 'index.css');
const outputPath = path.join(projectRoot, 'styles.css');

const entry = await fs.readFile(entryPath, 'utf8');

const importRegex = /@import\s+(?:url\()?['"]([^'"]+)['"]\)?\s*;/g;
const importPaths = Array.from(entry.matchAll(importRegex), match => match[1]);

if (importPaths.length === 0) {
    throw new Error(`No @import statements found in ${path.relative(projectRoot, entryPath)}`);
}

const resolvedImports = importPaths.map(importPath => {
    if (!importPath.startsWith('.')) {
        throw new Error(`Only relative @import paths are supported (got: ${importPath})`);
    }

    const absolutePath = path.resolve(path.dirname(entryPath), importPath);
    const relativePath = path.relative(projectRoot, absolutePath);
    if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
        throw new Error(`@import path must stay within project root (got: ${importPath})`);
    }

    return {
        absolutePath,
        relativePath: relativePath.split(path.sep).join(path.posix.sep)
    };
});

const sourceIndexPath = path.relative(projectRoot, entryPath).split(path.sep).join(path.posix.sep);

const header = [
    '/*',
    'Notebook Navigator - Plugin for Obsidian',
    'Copyright (c) 2025-2026 Johan Sanneblad',
    '',
    'This program is free software: you can redistribute it and/or modify',
    'it under the terms of the GNU General Public License as published by',
    'the Free Software Foundation, either version 3 of the License, or',
    '(at your option) any later version.',
    '',
    'This program is distributed in the hope that it will be useful,',
    'but WITHOUT ANY WARRANTY; without even the implied warranty of',
    'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',
    'GNU General Public License for more details.',
    '',
    'You should have received a copy of the GNU General Public License',
    'along with this program.  If not, see <https://www.gnu.org/licenses/>.',
    '',
    '=========================================================================',
    'GENERATED FILE - DO NOT EDIT styles.css',
    '=========================================================================',
    '',
    'Edit the CSS sources instead:',
    `- ${sourceIndexPath} (import order + per-file descriptions)`,
    '- src/styles/sections/*',
    '',
    'Generated by: scripts/build-styles.mjs',
    '*/',
    ''
].join('\n');

let output = header;

for (const entry of resolvedImports) {
    output += await fs.readFile(entry.absolutePath, 'utf8');
}

let existing = null;
try {
    existing = await fs.readFile(outputPath, 'utf8');
} catch {
    // styles.css may not exist yet
}

if (existing !== output) {
    await fs.writeFile(outputPath, output, 'utf8');
}

console.log(`Built styles.css from ${importPaths.length} files`);
